name: fancy_extensions
description: This package provides a collection of convenient Dart extensions for common operations, enhancing readability and improving code maintainability.
version: 0.0.4
homepage: https://github.com/Abdurahmon727/fancy_extensions
repository: https://github.com/Abdurahmon727/fancy_extensions
issue_tracker: https://github.com/Abdurahmon727/fancy_extensions/issues
# documentation: https://github.com/Abdurahmon727/fancy_extensions/tree/main/doc

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
